### ISSUE TITLE
[BUG] "Object is not iterable" issue

### ISSUE THREAD

**Issue by Laradefendini** [Badisi/wdio-harness#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Library version

latest

### Description

There was an "object is not iterable" issue when running wdio tests that use your library.

For now, we downgraded webdriverio version to 8.24.9 and @wdio/... versions to 8.24.8/8.24.9 and it is compatible with your _wdio-harness_ version 3.0.4. Eventually we will need to upgrade it when your version 3.0.5 is available.

I saw that you fixed it in your [latest commit](9e0260dd02820d78071842ce3815a6f43c16baf3).  Are you planning on releasing a new version so we can use it with the latests versions of angular and wdio ?

### Steps to reproduce

not needed as it has been fixed

**Comment by Badisi** [comment]
There is currently a regression with **Jasmine** typing in **webdriverio**.
So I was waiting for https://github.com/webdriverio/webdriverio/issues/11999 to get fixed.

But you will only have issues with `linting` (if you are doing lint) and special Jasmine methods like `.withContext`.
It does compiles and executes fine.

So I'll release a new version anyway.
Thanks for reporting

**Comment by Badisi** [comment]
🎉 Released in [@badisi/wdio-harness@3.1.0](https://github.com/Badisi/wdio-harness/releases/tag/3.1.0) 📦🚀

**Comment by Laradefendini** [comment]
Hi,

We are not using Jasmine on our case. Your fix in the latest version should be enough for us.

Thanks for your support.
